import inspect
from pathlib import Path
from typing import get_origin, Literal, get_args
from dataclasses import fields
from pandera.errors import SchemaErrors, SchemaError
from plotly.graph_objs import Figure
from shiny import ui, module, reactive, render
import pandas as pd
from asyncio import to_thread, sleep
from shinywidgets import render_widget, output_widget

from seroepi import estimators
from seroepi.app._utils import dt_download_server, dt_download_ui, format_metadata_ui, safe_plot_server, safe_plot_ui, \
    ColMapper, ui_task, generate_temp_download, _clean_ui_label, build_grouped_choices
from seroepi.client import PathogenwatchClient
from seroepi.constants import PlotType, EstimatorType, AggregationType, BayesianInferenceMethod, TemporalResolution, \
    SpatialResolution, Domain, GenotypeFlavour, DistanceFlavour
from seroepi.dist import GenomicDistances
from seroepi.io import PathogenwatchGenomeParser, BaseGenotypeParser
from seroepi.plotting import render_plot


@module.ui
def burden_ui():
    """UI layout for the data ingestion and global epidemiology dashboard."""
    return ui.layout_sidebar(
        ui.sidebar(
            ui.accordion(
                ui.accordion_panel(
                    "Dataset Registry 📂",
                    ui.tooltip(ui.input_select("active_dataset", "Active Dataset", choices=["Awaiting Data..."]),
                               "Select a previously loaded dataset to analyze or map.")
                ),
                ui.accordion_panel(
                "Load Data 💽",
                    ui.navset_pill(
                        ui.nav_panel(
                            ui.tooltip(
                                "Local Files 📁",
                                "Upload a pairwise SNP distance matrix (CSV) for genomic clustering "
                                "and network visualization."
                            ),
                            ui.div(
                                ui.tooltip(ui.input_file("genotype_file", "Genotype file (Required)",
                                                         accept=[".csv"]),
                                           "Upload a CSV file containing genotypes, such as those generated by "
                                           "Kleborate."),
                                ui.input_select("genotype_flavour", "Genotype Format", choices=GenotypeFlavour.ui_labels()),
                                ui.tooltip(ui.input_file("distance_file", "Distance Matrix (Optional)",
                                                         accept=[".csv", ".tsv", ".txt", ".nwk", ".tree"]),
                                           "Upload a CSV/Tree file containing pairwise distances between your samples."),
                                ui.input_select("distance_flavour", "Distance Format", choices=DistanceFlavour.ui_labels()),
                                ui.tooltip(ui.input_file("metadata_file", "Metadata (Optional)",
                                                         accept=[".csv"]),
                                           "Upload a CSV file containing patient or environmental metadata "
                                           "(e.g., date, spatial) to merge with the genotype data."),
                                ui.output_ui("dynamic_meta_mapping"),
                                ui.hr(),
                                ui.input_action_button("btn_process", "Load Files", class_="btn-primary w-100"),
                                class_="mt-3"
                            )
                        ),
                        ui.nav_panel(
                            ui.tooltip("Pathogenwatch 🔭",
                                       "Select a Pathogenwatch collection from your account to import directly."),
                            ui.div(
                                ui.tooltip(ui.input_password("pw_api_key", "API Key"),
                                           "Your Pathogenwatch API key for authenticating secure downloads."),
                                ui.input_action_button("btn_fetch_pw", "Fetch Collections", class_="btn-secondary w-100 mb-3"),
                                ui.input_selectize("pw_collection", "Select Collection", choices=[]),
                                ui.hr(),
                                ui.input_action_button("btn_load_pw", "Load Collection", class_="btn-primary w-100"),
                                class_="mt-3"
                            )
                        ),
                        # ui.nav_panel(
                        #     ui.tooltip("Kaptive-Web 🕷️",
                        #                "Select Kaptive-Web results from your account to import directly."),
                        #     ui.div(
                        #         ui.tooltip(ui.input_password("kw_api_key", "API Key"),
                        #                    "Your Kaptive-Web API key for authenticating secure downloads."),
                        #         ui.input_action_button("btn_fetch_kw", "Fetch Results", class_="btn-secondary w-100 mb-3"),
                        #         ui.input_selectize("kw_collection", "Select Results", choices=[]),
                        #         ui.hr(),
                        #         ui.input_action_button("btn_load_kw", "Load Results", class_="btn-primary w-100"),
                        #         class_="mt-3"
                        #     )
                        # ),
                    ),
                    ui.hr(),
                    ui.input_action_button("btn_clear_data", "Clear All Data", class_="btn-outline-danger w-100")
                ),
                ui.accordion_panel(
                    "Cluster Generation 🕸️",
                    ui.navset_pill(
                        ui.nav_panel(
                            "Genomic 🧬",
                            ui.div(
                                ui.p("Identify genomic clusters using a SNP distance matrix.", class_="text-muted small mb-3"),
                                ui.tooltip(ui.input_numeric("snp_threshold", "SNP Threshold", value=20),
                                           "Maximum single nucleotide polymorphisms (SNPs) between isolates to "
                                           "consider them part of the same genomic cluster."),
                                ui.input_action_button("btn_calc_snp_clusters", "Calculate Clusters", class_="btn-primary w-100 mt-2"),
                                class_="mt-3"
                            )
                        ),
                        ui.nav_panel(
                            "Transmission 🏥",
                            ui.div(
                                ui.p("Identify outbreaks based on spatial and temporal proximity.", class_="text-muted small mb-3"),
                                ui.tooltip(ui.input_selectize("trans_clone_col", "Clone Column", choices=[], selected=""),
                                           "The column defining a bacterial clone or lineage (e.g., ST) to "
                                           "restrict transmission bounds."),
                                ui.tooltip(ui.input_numeric("trans_spatial_thr", "Spatial Dist (km)", value=10.0),
                                           "Maximum geographical distance (in kilometers) between cases to link "
                                           "them in a transmission cluster."),
                                ui.tooltip(ui.input_numeric("trans_temporal_thr", "Temporal Dist (days)", value=20),
                                           "Maximum time gap (in days) between cases to link them in a "
                                           "transmission cluster."),
                                ui.input_action_button("btn_calc_trans_clusters", "Calculate Clusters", class_="btn-primary w-100 mt-2"),
                                class_="mt-3"
                            )
                        )
                    )
                ),
                ui.accordion_panel(
                    "Prevalence Aggregation 🧮",
                    ui.tooltip(ui.input_selectize("prev_trait", "Trait Column (Required)", choices=[]),
                               "The specific genetic trait to measure. This field is required to aggregate your data."),
                    ui.tooltip(
                        ui.input_radio_buttons(
                            "prev_agg_type",
                            "Aggregation Mode",
                            choices={
                                AggregationType.COMPOSITIONAL.value: "Compositional 🎵🎶",
                                AggregationType.TRAIT.value: "Trait ➕➖"
                            },
                            selected=AggregationType.COMPOSITIONAL.value
                        ),
                        "Compositional calculates the proportion of variants within a group. "
                        "Trait calculates the simple presence/absence of a specific marker."
                    ),
                    ui.tooltip(ui.input_selectize("prev_stratify", "Stratify By", choices=[], multiple=True,
                                                  options={"placeholder": "Optional, none selected..."}),
                               "Variables to group the data by (e.g., Spatial, Date) before calculating prevalence."),
                    ui.tooltip(ui.input_selectize("prev_cluster", "Cluster Column (Optional)", choices=[],
                                                  options={"placeholder": "Optional, none selected..."}),
                               "A cluster variable (e.g., Transmission Cluster, Hospital) to adjust the "
                               "prevalence estimates for sampling bias/outbreaks."),
                    ui.tooltip(ui.input_text("prev_negative", "Negative Indicator", value="-"),
                               "The string or character in your data that indicates a trait is absent (commonly '-' or '0')."),
                    ui.input_action_button("btn_aggregate_prev", "Aggregate Data", class_="btn-primary w-100 mt-3")
                ),
                ui.accordion_panel(
                    "Prevalence Estimation 📈",
                    ui.tooltip(ui.input_select("prev_estimator", "Estimator", choices=EstimatorType.ui_labels()),
                               "The statistical model used to calculate prevalence and confidence intervals."),
                    ui.output_ui("estimator_params_ui"),
                    ui.output_ui("model_io_ui"),
                    ui.input_action_button("btn_estimate_prev", "Estimate Prevalence 🚀", class_="btn-success w-100")
                ),
                id="burden_accordion",
                open=["Dataset Registry 📂", "Load Data 💽"], multiple=True
            ),
            width=350
        ),
        ui.navset_card_tab(
            ui.nav_panel("Dataset 🔍", ui.output_ui("dashboard_content"), value="tab_dataset_preview"),
            ui.nav_panel("Aggregates 🧮", ui.output_ui("agg_data_content"), value="tab_aggregated_data"),
            ui.nav_panel("Estimates 📈", ui.output_ui("prev_summary_content"), value="tab_prevalence_data"),
            ui.nav_panel("Diagnostics 🩺", ui.output_ui("model_diagnostics_content"), value="tab_model_diagnostics"),
            ui.nav_panel(
                "Prevalence Plot 📊",
                ui.layout_sidebar(
                    ui.sidebar(
                        ui.tooltip(
                            ui.input_select(
                                "prev_plot_type",
                                "Plot Type",
                                choices={
                                    PlotType.FOREST.value: "Forest Plot",
                                    PlotType.COMPOSITION_BAR.value: "Composition Bar",
                                    PlotType.COMPOSITION_HEATMAP.value: "Composition Heatmap",
                                    PlotType.LONGITUDINAL_PREVALENCE.value: "Longitudinal Prevalence"
                                }
                            ),
                            "The visualization style for the estimated prevalence data."
                        ),
                        ui.hr(),
                        ui.h6("Export Settings", class_="mb-2"),
                        ui.tooltip(ui.input_select("plot_format", "Format", choices=["png", "pdf", "svg", "jpeg"]),
                                   "The image format for the exported plot."),
                        ui.tooltip(ui.input_numeric("plot_width", "Width (px)", value=1200), "Exported image width in pixels."),
                        ui.tooltip(ui.input_numeric("plot_height", "Height (px)", value=800), "Exported image height in pixels."),
                        ui.download_button("btn_download_plot", "Download Plot", class_="btn-outline-primary w-100"),
                        width=280
                    ),
                    safe_plot_ui("prev_plot")
                ),
                value="tab_prevalence_plot"
            ),
            ui.nav_panel(
                "Network 🕸️",
                ui.layout_sidebar(
                    ui.sidebar(
                        ui.tooltip(ui.input_selectize("network_color_col", "Color Nodes By", choices=[]),
                                   "Metadata or genotype column used to color the nodes in the network."),
                        ui.hr(),
                        ui.tooltip(
                            ui.input_radio_buttons(
                                "network_edge_type", 
                                "Edges to Plot", 
                                choices={"snp": "Genomic (SNP)", "trans": "Transmission", "none": "None"},
                                selected="snp"
                            ),
                            "The type of relationship to draw between isolates (nodes)."
                        ),
                        ui.panel_conditional(
                            "input.network_edge_type === 'snp'",
                            ui.tooltip(ui.input_numeric("network_snp_threshold", "SNP Edge Threshold", value=20),
                                       "Draw an edge between nodes if their SNP distance is less than or equal to this value.")
                        ),
                        width=280
                    ),
                    output_widget("cluster_network_plot")
                ),
                value="tab_cluster_network"
            ),
            id="main_dashboard_tabs"
        )
    )


@module.server
def burden_server(input, output, session, app_state: dict):
    shared_df = app_state["shared_df"]
    prev_results = app_state["prev_results"]
    fitted_estimator = app_state["fitted_estimator"]
    pw_collections_cache = app_state["pw_collections_cache"]
    shared_dist = app_state["shared_dist"]
    shared_trans_dist = app_state.setdefault("shared_trans_dist", reactive.Value(None))
    dataset_registry = app_state.setdefault("dataset_registry", reactive.Value({}))
    shared_agg_df = app_state["shared_agg_df"]

    # --- STAGE 0: DYNAMIC TAB VISIBILITY ---
    @reactive.Effect
    async def manage_tab_visibility():
        est = fitted_estimator.get()
        tabs = [
            ("tab_aggregated_data", shared_agg_df.get() is not None),
            ("tab_prevalence_data", prev_results.get() is not None),
            ("tab_prevalence_plot", prev_results.get() is not None),
            ("tab_model_diagnostics", est is not None and hasattr(est, 'diagnostics')),
            ("tab_cluster_network", shared_dist.get() is not None or shared_trans_dist.get() is not None)
        ]
        for tab, show in tabs:
            await session.send_custom_message("toggle_tab", {"tab": tab, "show": show})

    @reactive.Effect
    def manage_accordion_state():
        if shared_df.get() is None:
            ui.update_accordion("burden_accordion", show="Load Data 💽")
            
    @reactive.Effect
    def sync_dataset_dropdown():
        reg = dataset_registry.get()
        if not reg:
            ui.update_select("active_dataset", choices=["Awaiting Data..."])
            return
            
        choices = list(reg.keys())
        current = input.active_dataset()
        selected = current if current in choices else choices[-1]
        ui.update_select("active_dataset", choices=choices, selected=selected)

    @reactive.Effect
    def switch_dataset():
        reg = dataset_registry.get()
        selected = input.active_dataset()
        if reg and selected in reg:
            ds_dict = reg[selected]
            if shared_df.get() is not ds_dict["df"]:
                shared_df.set(ds_dict["df"])
                shared_dist.set(ds_dict["dist"])
                shared_trans_dist.set(ds_dict["trans_dist"])
                shared_agg_df.set(None)  # Reset aggregated state when jumping contexts

    # --- STAGE 1: DYNAMIC COLUMN MAPPING ---
    @render.ui
    def dynamic_meta_mapping():
        if not (meta_info := input.metadata_file()):
            return ui.div()  # Return nothing if no file

        try:
            # PEEK AT THE HEADERS: nrows=0 makes this parse instantly
            mapper = ColMapper(cols := pd.read_csv(Path(meta_info[0]["datapath"]), nrows=0).columns.tolist())

            # Inject a beautiful accordion with dropdowns
            return ui.accordion(
                ui.accordion_panel(
                    "Map Metadata Columns",
                    ui.p("Please match your columns to the required fields:", class_="text-muted small"),
                    ui.input_selectize("map_id", "Sample ID", choices=[""] + cols,
                                       selected=mapper.guess("map_id")),
                    ui.layout_column_wrap(
                        ui.input_selectize("map_date", "Temporal", choices=[""] + cols,
                                           selected=mapper.guess("map_date")),
                        ui.input_select("map_date_res", "Resolution", choices=TemporalResolution.ui_labels(),
                                        selected=TemporalResolution.UNKNOWN.value),
                        width=1 / 2
                    ),
                    ui.layout_column_wrap(
                        ui.input_selectize("map_spatial", "Spatial", choices=[""] + cols,
                                           selected=mapper.guess("map_spatial")),
                        ui.input_select("map_spatial_res", "Resolution", choices=SpatialResolution.ui_labels(),
                                        selected=SpatialResolution.UNKNOWN.value),
                        width=1 / 2
                    ),
                    ui.input_selectize("map_lat", "Latitude", choices=[""] + cols,
                                       selected=mapper.guess("map_lat")),
                    ui.input_selectize("map_lon", "Longitude", choices=[""] + cols,
                                       selected=mapper.guess("map_lon"))
                ),
                id="meta_accordion",
                open="Map Metadata Columns"
            )
        except Exception as e:
            return ui.div(f"Could not read metadata columns: {e}", class_="text-danger small")

    # --- STAGE 2: THE EXECUTION PIPELINE ---
    @reactive.Effect
    @reactive.event(input.btn_process)
    async def load_data():
        if not (genotype_info := input.genotype_file()):
            ui.notification_show("Kleborate output is required.", type="warning")
            return

        async with ui_task("Pipeline Error") as p:
            try:
                p.set(message="Reading and Merging Datasets...", value=20)
                await sleep(0)  # Yield to event loop to update UI

                metadata_kwargs = {}
                meta_path = None

                if metadata_info := input.metadata_file():
                    meta_path = Path(metadata_info[0]["datapath"])
                    metadata_kwargs = {
                        "id_col": input.map_id() or None,
                        "date_col": input.map_date() or None,
                        "date_res": input.map_date_res() or None,
                        "spatial_col": input.map_spatial() or None,
                        "spatial_res": input.map_spatial_res() or None,
                        "lat_col": input.map_lat() or None,
                        "lon_col": input.map_lon() or None
                    }

                    # Optional: Add a quick guard clause to ensure they actually mapped the ID
                    if not metadata_kwargs["id_col"]:
                        ui.notification_show("You must select a Sample ID column to merge metadata.", type="error")
                        return

                ds_name = genotype_info[0]["name"]
                ParserClass = BaseGenotypeParser.get_parser(input.genotype_flavour())
                df = await to_thread(
                    ParserClass.from_files,
                    genotype_path=Path(genotype_info[0]["datapath"]),
                    meta_path=meta_path,
                    meta_kwargs=metadata_kwargs,
                    dataset_name=ds_name
                )

                dist_obj = None
                if distance_info := input.distance_file():
                    p.set(message="Parsing Distances...", value=40)
                    await sleep(0)
                    dist_obj = await to_thread(GenomicDistances.from_file, Path(distance_info[0]["datapath"]), input.distance_flavour())

                p.set(message="Pipeline Complete!", value=100)
                await sleep(0)
                
                shared_df.set(df)
                shared_dist.set(dist_obj)
                shared_trans_dist.set(None)
                
                # Update Registry
                reg = dataset_registry.get().copy()
                reg[ds_name] = {"df": df, "dist": dist_obj, "trans_dist": None}
                dataset_registry.set(reg)
                
                ui.notification_show("Data successfully loaded.", type="message", duration=4)

            except SchemaError as e:
                failed_col = getattr(e.schema, 'name', 'Unknown Column')
                ui.notification_show(
                    f"Validation Error in column '{failed_col}'. See console for details.",
                    type="error", duration=15)
                print(f"SCHEMA ERROR CASES:\n{e.failure_cases}")
                shared_df.set(None)
                # Reset the UI input process by forcing the accordion to stay open
                ui.update_accordion("burden_accordion", show="Load Data 💽")
            except SchemaErrors as e:
                ui.notification_show("Validation Error: Multiple schema violations detected in the uploaded file.",
                                     type="error", duration=15)
                shared_df.set(None)
                ui.update_accordion("burden_accordion", show="Data Ingestion")

    # --- STAGE 2B: PATHOGENWATCH API PROTOTYPE ---
    @reactive.Effect
    @reactive.event(input.btn_fetch_pw)
    async def fetch_pw_collections():
        api_key = input.pw_api_key()
        if not api_key:
            ui.notification_show("Please enter an API Key.", type="warning")
            return

        async with ui_task("API Error") as p:
                p.set(message="Connecting to Pathogenwatch...", value=30)
                await sleep(0)

                def fetch_collections():
                    # Safely handle clients with or without context managers
                    if hasattr(PathogenwatchClient, '__enter__'):
                        with PathogenwatchClient(api_key) as client:
                            return client.get_collections()
                    else:
                        client = PathogenwatchClient(api_key)
                        return client.get_collections()

                raw_collections = await to_thread(fetch_collections)
                
                # Normalize response into a list (safely handles nested API JSON dicts)
                if isinstance(raw_collections, dict):
                    collections = raw_collections.get("data", raw_collections.get("collections", []))
                else:
                    collections = list(raw_collections)

                if not collections:
                    ui.notification_show("No collections found.", type="warning")
                    return

                # Helper to safely extract attributes from either dicts or Python objects
                def get_val(obj, key, default=""):
                    if isinstance(obj, dict):
                        return obj.get(key, default)
                    return getattr(obj, key, default)
                    
                collections.sort(key=lambda x: str(get_val(x, 'name')).lower() if get_val(x, 'name') else "")

                cache_map = {}
                choices_map = {"": "Select..."}
                for c in collections:
                    c_id = get_val(c, 'uuid', get_val(c, 'id'))
                    if c_id:
                        cache_map[c_id] = c
                        choices_map[c_id] = get_val(c, 'name') or "Unnamed Collection"

                pw_collections_cache.set(cache_map)
                ui.update_selectize("pw_collection", choices=choices_map)

                p.set(message="Collections fetched!", value=100)
                ui.notification_show(f"Found {len(collections)} collections.", type="message")

    @reactive.Effect
    @reactive.event(input.btn_load_pw)
    async def load_pw_collection():
        api_key = input.pw_api_key()
        selected_uuid = input.pw_collection()
        cache = pw_collections_cache.get()

        if not api_key or not selected_uuid or selected_uuid not in cache:
            ui.notification_show("Please fetch and select a collection.", type="warning")
            return

        collection = cache[selected_uuid]

        async with ui_task("Load Error") as p:
                name = collection.get("name", "Collection") if isinstance(collection, dict) else getattr(collection, "name", "Collection")
                p.set(message=f"Fetching genomes for {name}...", value=30)
                await sleep(0)

                def fetch_genomes():
                    if hasattr(PathogenwatchClient, '__enter__'):
                        with PathogenwatchClient(api_key) as client:
                            if hasattr(collection, 'get_genomes'):
                                return collection.get_genomes(client)
                            return client.get_genomes(collection.get('uuid', collection.get('id')))
                    else:
                        client = PathogenwatchClient(api_key)
                        if hasattr(collection, 'get_genomes'):
                            return collection.get_genomes(client)
                        return client.get_genomes(collection.get('uuid', collection.get('id')))

                raw_genomes = await to_thread(fetch_genomes)
                
                if isinstance(raw_genomes, dict):
                    genomes = raw_genomes.get("data", raw_genomes.get("genomes", []))
                else:
                    genomes = list(raw_genomes)

                if not genomes:
                    ui.notification_show("Collection is empty.", type="warning")
                    return

                p.set(message="Parsing to DataFrame...", value=80)
                await sleep(0)

                df = await to_thread(PathogenwatchGenomeParser.from_records, genomes, dataset_name=name)

                p.set(message="Pipeline Complete!", value=100)
                await sleep(0)

                shared_df.set(df)
                shared_dist.set(None)
                shared_trans_dist.set(None)
                
                # Update Registry
                reg = dataset_registry.get().copy()
                reg[name] = {"df": df, "dist": None, "trans_dist": None}
                dataset_registry.set(reg)
                
                ui.notification_show(f"Loaded {len(df)} genomes from Pathogenwatch.", type="message", duration=4)

    @reactive.Effect
    @reactive.event(input.btn_clear_data)
    def clear_data():
        for key, r_val in app_state.items():
            if key in ["pw_collections_cache", "results_registry", "vaccine_registry", "dataset_registry"]:
                r_val.set({})
            else:
                r_val.set(None)
        ui.notification_show("All data and results cleared.", type="message")
        ui.update_accordion("burden_accordion", show="Load Data 💽")

    # --- STAGE 2C: CLUSTER GENERATION ---
    @reactive.Effect
    @reactive.event(input.btn_calc_snp_clusters)
    async def calc_snp_clusters():
        df = shared_df.get()
        dist = shared_dist.get()

        if df is None:
            ui.notification_show("Please load data first.", type="warning")
            return
        if dist is None:
            ui.notification_show("Please upload a SNP distance matrix in the Data Ingestion tab.", type="warning")
            return

        async with ui_task("SNP Clustering Error") as p:
                p.set(message="Calculating SNP clusters...", value=30)
                await sleep(0)
                clusters = await to_thread(dist.get_clusters, threshold=input.snp_threshold())
                clusters.name = f"{Domain.CLUSTER.value}_snp_{input.snp_threshold()}"

                p.set(message="Merging to dataset...", value=70)
                await sleep(0)

                # Safely drop existing column if running the identical threshold twice to prevent Pandas overlap suffixes
                if clusters.name in df.columns:
                    df = df.drop(columns=[clusters.name])

                df = df.join(clusters, on='sample_id')
                shared_df.set(df)
                
                # Update Registry State
                reg = dataset_registry.get().copy()
                if (ds_name := input.active_dataset()) in reg:
                    reg[ds_name]["df"] = df
                    dataset_registry.set(reg)

                p.set(message="Done!", value=100)
                ui.notification_show(f"Successfully generated {clusters.name}", type="message")

    @reactive.Effect
    @reactive.event(input.btn_calc_trans_clusters)
    async def calc_trans_clusters():
        df = shared_df.get()
        if df is None:
            ui.notification_show("Please load data first.", type="warning")
            return
        if not input.trans_clone_col():
            ui.notification_show("Please select a Clone Column.", type="warning")
            return

        async with ui_task("Transmission Clustering Error") as p:
                p.set(message="Calculating transmission clusters...", value=40)
                await sleep(0)

                if not (df.epi.has_spatial and df.epi.has_temporal):
                    ui.notification_show("Transmission clustering requires both spatial and temporal metadata.",
                                         type="error")
                    return

                def run_trans_clusters():
                    net = df.epi.transmission_network(
                        clone_col=input.trans_clone_col(),
                        spatial_threshold_km=input.trans_spatial_thr(),
                        temporal_threshold_days=input.trans_temporal_thr()
                    )
                    labels = df.epi.transmission_clusters(
                        clone_col=input.trans_clone_col(),
                        spatial_threshold_km=input.trans_spatial_thr(),
                        temporal_threshold_days=input.trans_temporal_thr(),
                        network=net
                    )
                    return net, labels

                t_net, t_clusters = await to_thread(run_trans_clusters)
                shared_trans_dist.set(t_net)

                if t_clusters.name in df.columns:
                    df = df.drop(columns=[t_clusters.name])

                # Create a copy so Shiny recognizes it as a new object and triggers UI updates
                df = df.copy()
                df[t_clusters.name] = t_clusters
                shared_df.set(df)
                
                # Update Registry State
                reg = dataset_registry.get().copy()
                if (ds_name := input.active_dataset()) in reg:
                    reg[ds_name]["df"] = df
                    reg[ds_name]["trans_dist"] = t_net
                    dataset_registry.set(reg)

                p.set(message="Done!", value=100)
                ui.notification_show(f"Successfully generated {t_clusters.name}", type="message")

    # --- STAGE 3: PREVALENCE ANALYSIS WORKFLOW ---
    @reactive.Effect
    def update_prev_dropdowns():
        if (df := shared_df.get()) is not None:
            trait_choices = {"": "Select..."}
            trait_choices.update(build_grouped_choices(df.epi.genotypes, "Other Traits"))
            
            stratify_choices = build_grouped_choices(df.epi.stratify_cols, "Other Variables")
            
            cluster_choices = {"": "Select..."}
            cluster_choices.update(build_grouped_choices(df.epi.cluster_cols, "Clusters 🕸️"))

            ui.update_selectize("prev_trait", choices=trait_choices, selected="")
            ui.update_selectize("prev_stratify", choices=stratify_choices)
            ui.update_selectize("prev_cluster", choices=cluster_choices, selected="")
            
            # Default the transmission clone to ST if available
            st_col = f"{Domain.GENOTYPE.value}_ST"
            st_select = st_col if st_col in df.epi.genotypes else ""
            ui.update_selectize("trans_clone_col", choices=trait_choices, selected=st_select)

    @reactive.Effect
    def update_network_dropdowns():
        if (df := shared_df.get()) is not None:
            # Combine categories and remove duplicates while preserving order
            color_cols = list(dict.fromkeys(df.epi.stratify_cols + df.epi.cluster_cols + df.epi.genotypes))
            color_choices = {"": "Select..."}
            color_choices.update(build_grouped_choices(color_cols, "Other Variables"))
            
            ui.update_selectize("network_color_col", choices=color_choices, selected="")

    @render.ui
    def estimator_params_ui():
        est_type = input.prev_estimator()

        # Hide if a model has been uploaded since we won't be compiling it
        if "model_upload" in input and input.model_upload():
            return ui.div()

        try:
            estimator_class_name = EstimatorType(est_type).class_name
            EstimatorClass = getattr(estimators, estimator_class_name, None)
        except Exception:
            return ui.div()

        if not EstimatorClass:
            return ui.div()

        # Check for in-memory model
        est = fitted_estimator.get()
        if est and type(est).__name__ == estimator_class_name and getattr(est, 'is_fitted_', False):
            return ui.div(
                ui.hr(),
                ui.p(
                    "A fitted model of this type is currently in memory. "
                    "Prevalence will be predicted using this model's learned weights. "
                    "To train a new model, click 'Clear Fitted Model' below.",
                    class_="text-info small mb-1"
                )
            )

        # Safely inspect the signature
        sig = inspect.signature(EstimatorClass.__init__)
        elements = []

        # Dynamically build standard Shiny inputs depending on the annotated python Type
        for name, param in sig.parameters.items():
            # Exclude internal/inappropriate variables from the user UI
            if name in ['self', 'target_event', 'target_n', 'lat_col', 'lon_col']:
                continue

            input_id = f"est_param_{name}"
            label = name.replace("_", " ").title()
            default = param.default if param.default != inspect.Parameter.empty else None

            origin = get_origin(param.annotation)

            if param.annotation is int or param.annotation is float:
                elements.append(ui.input_numeric(input_id, label, value=default))
            elif param.annotation is bool:
                elements.append(ui.input_checkbox(input_id, label, value=default))
            elif origin is Literal:
                choices = get_args(param.annotation)
                choices_dict = {c: str(c).replace('_', ' ').title() for c in choices}
                elements.append(ui.input_select(input_id, label, choices=choices_dict, selected=default))
            elif 'InferenceMethod' in str(param.annotation):
                default_val = default.value if hasattr(default, 'value') else default
                elements.append(
                    ui.input_select(input_id, label, choices=BayesianInferenceMethod.ui_labels(), selected=default_val))

        if elements:
            return ui.div(ui.hr(), ui.p("Hyperparameters", class_="text-muted small mb-1"), *elements)
        return ui.div()

    @render.ui
    def model_io_ui():
        est_type = input.prev_estimator()
        try:
            estimator_class_name = EstimatorType(est_type).class_name
            EstimatorClass = getattr(estimators, estimator_class_name, None)
        except Exception:
            return ui.div()

        # Safely hide the UI if the estimator (like Frequentist) doesn't support model loading
        if not EstimatorClass or not hasattr(EstimatorClass, 'load_model'):
            return ui.div()

        elements = [
            ui.hr(),
            ui.p("Model Weights (Optional)", class_="text-muted small mb-1"),
            ui.input_file("model_upload", "Load Fitted Model (.pkl)", accept=[".pkl"])
        ]

        # If a model of the CURRENT type is fitted in memory, provide the download button
        est = fitted_estimator.get()
        if est and type(est).__name__ == EstimatorClass.__name__ and getattr(est, 'is_fitted_', False):
            elements.append(
                ui.download_button("model_download", "Download Fitted Model", class_="btn-outline-primary w-100 mb-2")
            )
            elements.append(
                ui.input_action_button("btn_clear_model", "Clear Fitted Model", class_="btn-outline-danger w-100 mb-3")
            )

        return ui.div(*elements)

    @reactive.Effect
    @reactive.event(input.btn_clear_model)
    def clear_model():
        fitted_estimator.set(None)
        ui.notification_show("Fitted model cleared from memory.", type="message")

    @render.download(filename=lambda: f"fitted_{EstimatorType(input.prev_estimator()).name.lower()}_model.pkl")
    def model_download():
        est = fitted_estimator.get()
        if est and getattr(est, 'is_fitted_', False):
            return generate_temp_download(est.save_model, ".pkl", "Model Export Error")

    @reactive.Effect
    @reactive.event(input.btn_aggregate_prev)
    async def aggregate_prevalence():
        if (df := shared_df.get()) is None:
            ui.notification_show("Please upload and process data first.", type="warning")
            return

        trait = input.prev_trait() or None
        cluster = input.prev_cluster() or None
        agg_mode = input.prev_agg_type()

        if not trait:
            ui.notification_show("Please select a Trait Column before aggregating.", type="warning")
            return

        stratify = list(input.prev_stratify())

        if agg_mode == AggregationType.TRAIT and not stratify:
            ui.notification_show("Trait prevalence requires at least one stratification column.", type="error")
            return

        # INTENT ROUTING: 
        # If the user wants a compositional breakdown, the trait column acts as the primary grouping variable!
        if agg_mode == AggregationType.COMPOSITIONAL and trait:
            if trait not in stratify:
                stratify.append(trait)
            trait_col = None  # Leave None so the accessor groups compositionally by the last strata
        else:
            trait_col = trait

        async with ui_task("Aggregation Error") as p:
                p.set(message="Aggregating data...", value=20)
                await sleep(0)

                def run_aggregation():
                    return df.epi.aggregate_prevalence(
                        stratify_by=stratify,
                        trait_col=trait_col,
                        cluster_col=cluster,
                        negative_indicator=input.prev_negative()
                    )

                agg_df = await to_thread(run_aggregation)

                shared_agg_df.set(agg_df)
                p.set(message="Done!", value=100)
                ui.notification_show("Data aggregated successfully!", type="message")
                ui.update_accordion("burden_accordion", show="Prevalence Estimation 📈")
                ui.update_navset("main_dashboard_tabs", selected="tab_aggregated_data")


    @reactive.Effect
    @reactive.event(input.btn_estimate_prev)
    async def estimate_prevalence():
        if (agg_df := shared_agg_df.get()) is None:
            ui.notification_show("Please aggregate data first.", type="warning")
            return

        est_type = input.prev_estimator()

        async with ui_task("Calculation Error") as p:
                p.set(message="Instantiating estimator...", value=20)
                await sleep(0)

                estimator_class_name = EstimatorType(est_type).class_name

                if not hasattr(estimators, estimator_class_name):
                    ui.notification_show(f"{estimator_class_name} is not available. Did you install seroepi[models]?",
                                         type="error")
                    return

                EstimatorClass = getattr(estimators, estimator_class_name)

                # Check if we have a model already compiled and fitted in memory
                in_memory_est = fitted_estimator.get()
                can_reuse_memory = (
                        in_memory_est is not None
                        and type(in_memory_est).__name__ == EstimatorClass.__name__
                        and getattr(in_memory_est, 'is_fitted_', False)
                )

                # Intercept the model upload input if it exists
                file_info = input.model_upload() if "model_upload" in input else None

                if hasattr(EstimatorClass, 'load_model') and file_info:
                    p.set(message="Loading model...", value=40)
                    await sleep(0)
                    try:
                        est = EstimatorClass.load_model(Path(file_info[0]["datapath"]))
                    except Exception as e:
                        ui.notification_show(f"Failed to load model: {str(e)}", type="error", duration=10)
                        return

                    p.set(message="Predicting prevalence...", value=60)
                    await sleep(0)
                    res = await to_thread(est.predict, agg_df)
                elif can_reuse_memory:
                    p.set(message="Using in-memory fitted model...", value=60)
                    await sleep(0)
                    est = in_memory_est
                    res = await to_thread(est.predict, agg_df)
                else:
                    # Dynamically extract and assign kwargs for the selected estimator class
                    kwargs = {}
                    sig = inspect.signature(EstimatorClass.__init__)
                    for name, param in sig.parameters.items():
                        if name in ['self', 'target_event', 'target_n', 'lat_col', 'lon_col']:
                            continue

                        input_id = f"est_param_{name}"
                        if input_id in input:
                            val = input[input_id]()
                            if val == "":  # Skip empty numeric inputs to fallback on defaults
                                continue

                            origin = get_origin(param.annotation)

                            if param.annotation is int:
                                kwargs[name] = int(val)
                            elif param.annotation is float:
                                kwargs[name] = float(val)
                            elif param.annotation is bool:
                                kwargs[name] = bool(val)
                            elif origin is Literal:
                                kwargs[name] = val
                            elif 'InferenceMethod' in str(param.annotation):
                                kwargs[name] = BayesianInferenceMethod(val)
                            else:
                                kwargs[name] = val

                    # Ensure SpatialPrevalenceEstimator maps correctly to Pandas generated columns
                    if estimator_class_name == "SpatialPrevalenceEstimator":
                        kwargs['lat_col'] = 'latitude'
                        kwargs['lon_col'] = 'longitude'

                    est = EstimatorClass(**kwargs)

                    p.set(message="Fitting model and calculating...", value=60)
                    await sleep(0)
                    res = await to_thread(est.calculate, agg_df)

                fitted_estimator.set(est)
                prev_results.set(res)
                
                # Cache the run dynamically so it can be picked up by the Formulation tab!
                registry = app_state.setdefault("results_registry", reactive.Value({})).get().copy()
                trait_clean = _clean_ui_label(res.trait)
                strata_str = ", ".join([_clean_ui_label(s) for s in res.stratified_by]) if res.stratified_by else "Global"
                ds_name = df.attrs.get("dataset_name", "Unknown Dataset")
                run_name = f"[{ds_name}] {trait_clean} by {strata_str} ({EstimatorType(est_type).name.title()})"
                registry[run_name] = {"res": res, "est": est, "agg_df": agg_df}
                app_state["results_registry"].set(registry)

                ui.notification_show("Prevalence calculated successfully! Check the plot tab.", type="message")
                p.set(message="Done", value=100)
                ui.update_navset("main_dashboard_tabs", selected="tab_prevalence_plot")
                await sleep(0)

    # --- STAGE 4: RENDERING THE DASHBOARDS ---
    @render.ui
    def dashboard_content():
        if (df := shared_df.get()) is None:
            return ui.div("Please upload and process files to view the global dataset.",
                          class_="text-center mt-5 text-muted fs-4")

        return dt_download_ui("dashboard", "Global Dataset Preview")

    dt_download_server("dashboard", data_callable=lambda: shared_df.get(), filename="global_dataset.csv")

    @render.ui
    def agg_data_content():
        if (agg_df := shared_agg_df.get()) is None:
            return ui.div("Please aggregate data in the sidebar to view the aggregated dataset.",
                          class_="text-center mt-5 text-muted fs-4")

        meta_dict = agg_df.attrs.get('metric_meta', {})
        meta_ui = format_metadata_ui(meta_dict)

        return ui.div(
            ui.card(ui.card_header("Aggregates Metadata"), ui.div(*meta_ui, class_="p-2")),
            dt_download_ui("agg_data", "Aggregates Data")
        )

    dt_download_server("agg_data", data_callable=lambda: shared_agg_df.get(), filename="aggregated_data.csv")

    @render.ui
    def prev_summary_content():
        if (res := prev_results.get()) is None:
            return ui.div("Calculate prevalence to view the results data.", class_="text-center mt-5 text-muted fs-4")

        # Dynamically extract instance attributes into a dictionary
        meta_dict = {f.name: getattr(res, f.name) for f in fields(res) if
                     f.name not in ['data', 'model_results']}
        meta_ui = format_metadata_ui(meta_dict)

        return ui.div(
            ui.card(ui.card_header("Estimates Metadata"), ui.div(*meta_ui, class_="p-2")),
            dt_download_ui("prev_summary", "Estimates Data")
        )

    dt_download_server("prev_summary", data_callable=lambda: prev_results.get().data if prev_results.get() else None,
                       filename="estimates_data.csv", height="400px")

    @render.ui
    def model_diagnostics_content():
        if (est := fitted_estimator.get()) is None:
            return ui.div("Estimate prevalence to view model diagnostics.", class_="text-center mt-5 text-muted fs-4")

        if not hasattr(est, 'diagnostics'):
            return ui.div(
                ui.p(f"Diagnostics are not applicable for {type(est).__name__}."),
                class_="text-center mt-5 text-muted fs-4"
            )

        try:
            # Execute a dummy call to gracefully catch TypeErrors (like attempting diagnostics on SVI)
            _ = est.diagnostics()
            return dt_download_ui("model_diagnostics", "NumPyro Posterior Diagnostics")
        except Exception as e:
            return ui.div(f"Diagnostics Error: {str(e)}", class_="text-danger text-center mt-5 fs-5")

    def get_model_diagnostics():
        if (est := fitted_estimator.get()) is not None and hasattr(est, 'diagnostics'):
            try:
                return est.diagnostics()
            except Exception:
                pass
        return None

    dt_download_server("model_diagnostics", data_callable=get_model_diagnostics, filename="model_diagnostics.csv",
                       height="500px")

    safe_plot_server("prev_plot", data_reactive=prev_results, plot_type=input.prev_plot_type)

    @render.download(filename=lambda: f"prevalence_plot.{input.plot_format()}")
    def btn_download_plot():
        res = prev_results.get()
        if res is None:
            ui.notification_show("No plot data available to export.", type="warning")
            return

        # Generate the raw Plotly Figure (go.Figure) from the router
        fig = render_plot(res, input.prev_plot_type())

        # Kaleido naturally intercepts write_image locally
        def save_fig(p: Path):
            fig.write_image(p, format=input.plot_format(), width=input.plot_width(), height=input.plot_height())

        return generate_temp_download(save_fig, f".{input.plot_format()}", "Plot Export Error")

    @reactive.Calc
    async def network_layout():
        dist = shared_dist.get()
        
        # Always prefer genomic distances for the layout to maintain a stable coordinate 
        # space when toggling transmission edges!
        if dist is not None:
            layout_net = dist
        else:
            trans_dist = shared_trans_dist.get()
            if trans_dist is not None:
                layout_net = trans_dist
            else:
                return None

        async with ui_task("Layout Error") as p:
            p.set(message="Preparing distance matrix...", value=20)
            await sleep(0)  # Flush UI

            p.set(message="Calculating network layout (MDS)...", value=50)
            await sleep(0)

            # 2. Generate 2D Layout using Multi-Dimensional Scaling
            # n_init=1 and max_iter=100 keeps it lightning fast for Shiny UI!
            pos = await to_thread(layout_net.layout)

            p.set(message="Layout complete!", value=100)
            await sleep(0)

            return pos

    @render_widget
    async def cluster_network_plot():
        df = shared_df.get()
        dist = shared_dist.get()
        trans_dist = shared_trans_dist.get()

        empty_theme = dict(plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)', font=dict(color='#94A3B8'))

        if df is None:
            return Figure().update_layout(title="Upload a dataset in Tab 1 to view the network.", **empty_theme)
            
        # Route layout to match network_layout preference exactly
        if dist is not None:
            primary_net = dist
        elif trans_dist is not None:
            primary_net = trans_dist
        else:
            return Figure().update_layout(title="Upload a distance matrix or calculate transmission clusters.", **empty_theme)

        pos = await network_layout()
        if pos is None:
            return Figure().update_layout(title="Processing distance matrix...", **empty_theme)

        # Call the standalone plot renderer directly!
        return render_plot(
            primary_net,
            PlotType.NETWORK,
            df=df,
            pos=pos,
            edge_type=input.network_edge_type(),
            threshold=input.network_snp_threshold(),
            color_col=input.network_color_col(),
            trans_network=trans_dist
        )
